name: Automated Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Update Pull Request Status
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/check-runs \
          -d '{"name": "Automated Tests", "head_sha": "${{ github.sha }}", "status": "completed", "conclusion": "success", "output": {"title": "Tests Passed", "summary": "All tests passed successfully."}}'
